// <auto-generated />
using Eventos.DataAcessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Eventos.DataAcessLayer.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20180303165304_AdicionandoTabelaParticipante")]
    partial class AdicionandoTabelaParticipante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Eventos.DataAcessLayer.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Data");

                    b.Property<int>("FaixaEtaria");

                    b.Property<TimeSpan?>("HoraFim");

                    b.Property<TimeSpan?>("HoraIncio");

                    b.Property<int>("IngressosVendidos");

                    b.Property<string>("Local")
                        .IsRequired();

                    b.Property<int>("MaximoIngressos");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<bool>("OpenBar");

                    b.Property<int>("QuantidadeDeAmbientes");

                    b.HasKey("IdEvento");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Eventos.DataAcessLayer.Models.Participante", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("EventoIdEvento");

                    b.Property<string>("NomeParticipante")
                        .IsRequired();

                    b.HasKey("IdEvento");

                    b.HasIndex("EventoIdEvento");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("Eventos.DataAcessLayer.Models.Participante", b =>
                {
                    b.HasOne("Eventos.DataAcessLayer.Models.Evento", "Evento")
                        .WithMany("Participantes")
                        .HasForeignKey("EventoIdEvento");
                });
#pragma warning restore 612, 618
        }
    }
}
